language: java
install: true
jdk: openjdk8
script: chmod resources/forgerockDependencies.sh 777 && resources/forgerockDependencies.sh && mvn clean exec:exec && mvn clean install -P openwis -fae -DskipTests -Dfile.encoding=UTF-8 --fail-at-end
cache:
  directories:
  - $HOME/.m2
