sudo: false

language: java

jdk: openjdk8

script:
  - mvn clean install -Pdependencies,openwis,admin
  - mvn clean install -Puser

notifications:
  email:
    recipients:
      - openwis-travis@meteo.fr
    on_success: change
    on_failure: change