language: java
install: true
jdk: openjdk8
script: chmod 777 resources/forgerockDependencies.sh && resources/forgerockDependencies.sh && mvn clean exec:exec && mvn clean install -P openwis -fae -DskipTests -Dfile.encoding=UTF-8
cache:
  directories:
  - $HOME/.m2
before_deploy:
- cd ..
- tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz -C **/*.jar
deploy:
  provider: releases
  api_key: $GITHUBOAUTH
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  draft: true
  on:
    branch: travis-ci
