sudo: false

language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: "openwis"
    token:
      secure: ${sonar_token}

before_install:
- openssl aes-256-cbc -K $encrypted_62b1a583e357_key -iv $encrypted_62b1a583e357_iv
  -in resources/travis_copy_artifacts_rsa.enc -out /tmp/travis_copy_artifacts_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_copy_artifacts_rsa
- ssh-add /tmp/travis_copy_artifacts_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- mvn clean install -Pdependencies,openwis,admin
- mvn clean install -Puser -Pjacoco-coverage sonar:sonar

after_success: tar acf openwis_artifacts.tar.gz openwis-dataservice/openwis-dataservice-server/openwis-dataservice-server-ear/target/openwis-dataservice.ear openwis-dataservice/openwis-dataservice-config/target/openwis-dataservice-config-files.zip openwis-harness/openwis-harness-client/target/openwis-harness-client.jar openwis-securityservice/openwis-securityservice-war/target/openwis-securityservice.war openwis-metadataportal/openwis-portal/openwis-user-portal/openwis-user-portal-user.war openwis-metadataportal/openwis-portal/openwis-admin-portal/openwis-admin-portal-admin.war openwis-metadataportal/openwis-portal-solr/target/openwis-portal-solr.war openwis-stagingpost/target/stagingPost.war openwis-management/openwis-management-service/openwis-management-service-ear/target/openwis-management-service.ear

deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/openwis_artifacts.tar.gz ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: cicd_integration

notifications:
  email:
    recipients:
    - openwis-travis@meteo.fr
    on_success: change
    on_failure: change

env:
  global:
  - secure: HMhlfrn9UmSd5IPND82xlWrCYMQz/lga20JHO7nSPFT+qOdApNSdfPecG2MEMS7Ry8n8NOfNth6kNjaB4y7KVb9d3UPSBIbs6+whhPUWG6NXDCjQcUAAaMdxzTF60h3sg6x4BnnJUwaUKiOYWtRITivRJ2OD/uN3LPg1e5Mnwdh+MvDU1rR00k3UAuO+2uxziZjFsha0NTAXj/GoJput7g7+p3vbNPdsohSP94Tj3pjOOk7UKHNpfh8JYePKBWQDjwpkivY5dL8xUYzybkFqdY/cVQGEKFoD3tNEynvRqTSs4onEvH7qH1caU4vLJNluI1uJ9vDsZs0PpZT+hGF0UAIKdB0S+Xkhfk67qxRHa8mzMKCqW1SQDtKqCCcF8pNbgdh73An4sGhmbhA9SU7r5kf8LZ1tytSaZ3JwB6lGBFlygFV7biv+Su0PR13lFSB4hMMC9EOicoT1VFFAdMePD9DrzKvWpxtJQFXvAAPDkNV76SOE+V5fNtLXaYuIhTPbJ20lqRh6GuapcxymuhLgFy7gbmTGZ9Q54h+KCahlZ1UWY+ZhGmbCHgBueC10J4cDL7l8LakLRmJEZ3Eu63a2rBqtcoeCGlPXLOJQP4TNvh/s7eGC4DtkOP1xNVoQS/QGpPAcGYpRg6WqQBpW93hKJjSfcW4baUm6t7CPyUzw2RQ=
  - secure: YMlqqbP1fc3+LxnyCOWy3j4I6FQrecIO5uUtbXMSOx/2dJB8MqelLhpMUawbRDGo36OY+bjKB7QnzakczBBhkG1zahp8r7fKcPyDmlzRRrj8GHDpXtrzq+yAqIHYuAOp7zadU97UKmteT5AvT+hRL3UQElAWLVMIgOTvO7w5GV6KHbrkisb6+utxgALtUWOzTJlMJi8SnVaNfEeFP3QN3iZR2mZDFWDJqcdsgJVL5nZe0Dk1+70TW/pDP/aLnXrtENrbTahC2s1jzJHGJbcOSQtsK7nUwUJePLxbdReCiyBoup0NLghzl2un2yDbX6wdjdXfi3kye2jXv6SyOzwnuCfStv9P0SZIwzfJGBswaa+4bMH0CkYBq7GjOZSNkVdH2GUxxbezICzp16O3qWYll7zieAM24HwH1c+eeP7xJd6lyhKWeIwKMdbpHnXukfm863EJoTPjD15uv6dqiamWDAAMG7b4rHhZ79qyeHNT4RLXGc61oPnGfQSsgVhr6W2A61J1lAori33dEgqWikLrPEvWLQsS68UzqJ0RKWi5X4CBn0VVyXRLQOZ5O1tzLk6HRTzeSTj4D3NUV01i6r0NS9XhchkFQ8S8nGxcOEmUPXyf1dFQ1RTQK3m6UGIfCRV2a1Q8IZ4cv4ggurMzXpqx9DZdb424/22UkfesFFbjpV8=
  - secure: OZYV39+d6D8kLtk2WzXCHg4cJO70BDezgI8JxSFK2c5M0djiArfmDLsZJrMI8HFV2Sow1ByT7+FHSD73r/bQbuF7QOxI7TnoNgYCfgUL+nXi9f5upQXDMT7udhi0OI4qOu+1tVRe1FO9loMG5q24XJNghsQxd8KfK7IeIoG+XvIKQAQYPsMNj4cX6Y2Z7vOWOtP3d3JKHzqer6wsDj/SpO4tWI9Y5az9iO1XR2jMtroPnGRRrL7R1UqAplecJCk0Cs/kCeer5WnTXtJ+bPUwv9b8gvuT0rP2RFFNmfdmd7Fr/HoY5yHlZ6LvcM/scFijHWiGbViPIaSn0IAEU/pU5DshanJ4DfxsjR8GDQFnqZms28H6X5/N+WMu3lFTMnEWPM2ZX91kzJcAQ6uJ7Y+DXCyFfxhDfRw9q5MsZHeaAPx+3vVMclGNTHdlEvbSRZkKaJP892eH8Ys5xqdmCTAtpYVWWPd9FrxEBYeBE1nCqERhZ419VbORq7gEHMApNHqp7T1xDuCYmu+n+XYpzc/DcQMIh7LyQ6uEvUzOKPgDXu/3K5ww0MG0wSVKVpc94LoFszEya5jD8+wvBWoGg9GIwBxzRhjVUEjNZV/wngzvbVQ9u6GidTXud22YHkeWMEELhL8R9U0BsEqAqps2LQqXvmsBDyJ4L8mAI4ynpga2cWk=