sudo: false

language: java

jdk: openjdk8

script:
  - mvn clean install -Pdependencies,openwis,admin -DskipTests=true
  - mvn clean install -Popenwis,user

notifications:
  email:
    recipients:
      - openwis-travis@meteo.fr
    on_success: always
    on_failure: always